[workspace]
members = ["src/ic_side_services_backend", "src/flux_types", "src/http_over_ws", "src/logger"]
resolver = "2"

[workspace.package]
edition = "2021"

[workspace.dependencies]
serde = "1.0.193"
serde_json = "1.0.108"
candid = "0.9.3"
ic-cdk = "0.10.0"
ic-cdk-macros = "0.7.1"
ic-websocket-cdk = "0.3.2"
serde_cbor = "0.11.2"

